### ISSUE TITLE
[feat] Command - USER

### ISSUE THREAD

**Issue by LWJ0513** [42Seoul-ft-irc/ft_irc#18]
![he](https://file3.instiz.net/data/file3/2018/02/03/f/2/7/f27d459dbdb8a0a34dd5a3f20b7d3a12.gif)

## Description

```
	Command: USER
     Parameters: <username> <hostname> <servername> <realname>
``` 

연결을 시작할 때 새 사용자의 사용자명, 호스트명, 서버명 및 실명을 지정한다.
~~- 클라이언트가 NICK와 USER 모두를 수신한 후에만 사용자가 등록된다.  -> 등록은 플래그로 확인한다.~~
- 호스트명과 서버명은 보안상의 이유로 직접 연결된 클라이언트에서는 일반적으로 IRC 서버에 의해 무시된다.
- realname 매개변수는 마지막 매개변수이어야 하며, 이는 공백 문자를 포함할 수 있으며 반드시 콜론(':')으로 접두어를 붙여야 한다.
`USER <username> <hostname> <servername> :<realname>`
- 맨 앞에 전치사가 붙는 것은 서버간의 통신이므로 구현하지 않는다.
<br>

## Numeric Replies

           ERR_NEEDMOREPARAMS              ERR_ALREADYREGISTRED

###  461 ERR_NEEDMOREPARAMS
```
                        "<command> :Not enough parameters"
``` 
클라이언트에게 서버로부터 반환된 다양한 명령들에 대해, 클라이언트가 충분한 매개변수를 제공하지 않았을 때 반환된다.

### 462 ERR_ALREADYREGISTRED
                        ":You may not reregister"

서버가 등록된 세부 정보의 일부를 변경하려는 모든 링크에 반환된다.
이는 두 번째 USER 메시지에서 비밀번호 또는 사용자 세부 정보를 변경하려는 시도를 나타낸다.
<br>
## Example
```
USER guest tolmoon tolsun :Ronnie Reagan
        ; User registering themselves with a username of "guest" and real name "Ronnie Reagan".
``` 

## Message
- IRC 메시지는 항상 CR-LF(Carriage Return`\r` - Line Feed`\n`) 쌍으로 종료된다.
- CR-LF를 포함하여 모든 문자를 세어 512자를 초과해서는 안 된다.
- 따라서 명령과 해당 매개변수에는 최대 510자가 허용된다.
- 빈 메세지는 무시한다.
- CR과 LF를 메시지 구분자로 지정한다.

### username, hostname, servername 
- 공백, NUL, CR, LF를 포함하지 않으며 시작 문자가 : 이어서는 안 된다.
- 공백으로 구분된다.
### realname 
- 앞에 : 가 붙는다.
- 공백이 올 수 있다.
- NUL, CR, LF가 올 수 있다.

<br>

## CHECK
- [ ] 파라미터의 수가 많을 경우 처리
- [ ] 만약 split 에서 접두사 설정이 추가되었을 때 예외처리 (USER는 접두사를 받지 않는다.)
<br>

## TODO
- [x] PASS를 통과한 유저인지 확인한다.
- [x] 이미 추가되어 있는 유저인지 확인한다. -> fd로? USER 플래그로 확인
   - [x] 추가 되어 있을 경우 ERR_ALREADYREGISTRED 발생
   근데 irssi 를 쓸 경우 USER가 다시 들어올 일이 없음 (userhost 로 변환되어 넘어옴)
- [x] 들어온 파라미터의 개수를 확인한다.
   - [x] 만약 파라미터 수가 더 많으면?
          그 앞에 것만 처리하고 뒤에는 무시한다.
   - [x] 적을 경우 ERR_NEEDMOREPARAMS 발생
- [x] 제대로 들어왔을 때
   - [x] 데이터 유효성 검사
      - [x] realname 들어왔는지 확인
   - [x] username 저장
   - [x] hostname 저장
   - [x] servername저장
   - [x] realname 저장
   - [x] USER 플래그 변경
