### ISSUE TITLE
[feat] Authorization

### ISSUE THREAD

**Issue by LWJ0513** [42Seoul-ft-irc/ft_irc#19]
![he](https://mblogthumb-phinf.pstatic.net/MjAxNzA0MjZfMjMx/MDAxNDkzMTMzODcwMzcw.i51_qDnTMqtM-D6RODGHS2kXQ-Tj2-1xziNLjz9_g-0g.HBIIH20uFNw47s7Ty2Z-8RmMTT4xyZzhLUUkIZJpWXUg.GIF.untri0624/1488983702296.GIF?type=w800)
<br>

## Description
- 클라이언트에 대해 다음과 같은 정보를 가지고 있어야 한다.
    - nickname
    - real name
    - user name
- PASS, NICK, USER 가 모두 인증되었을 때 사용자를 등록한다.
- RC 서버에 연결하면 클라이언트는
    - 현재 사용자/~~서버~~ 수 (LUSER 명령에 따라)와 함께 MOTD(Message of the Day)가 전송된다.
    - 또한, 서버는 클라이언트에게 자신의 이름과 버전, 그리고 적절하다고 생각되는 다른 소개 메시지를 명확하게 전달해야 한다.

 
<br>

## Numeric Replies
```
 375 - 372 - 376
``` 

- 숫자 응답은 발신자 접두어, 세 자리 숫자 및 응답 대상으로 구성된 하나의 메시지로 보내져야 한다.
- 숫자 응답은 일반 메시지와 동일하지만 키워드는 문자열이 아니라 3자리 숫자로 이루어져 있다.
<br>

### 375 RPL_MOTDSTART
``` 
:- <server> Message of the day - 
``` 

### 372 RPL_MOTD
```
:- <text>
``` 

### 376 RPL_ENDOFMOTD
```
:End of /MOTD command
``` 

### 251 RPL_LUSERCLIENT
```
:There are <integer> users and <integer> invisible on <integer> servers
``` 

### 252 RPL_LUSEROP
```
<integer> :operator(s) online
``` 

### 253 RPL_LUSERUNKNOWN
```
<integer> :unknown connection(s)
``` 

###  254 RPL_LUSERCHANNELS
```
<integer> :channels formed
``` 

### 255 RPL_LUSERME
```
:I have <integer> clients and <integer> servers
``` 

LUSERS" 메시지를 처리하는 과정에서 서버는 RPL_LUSERCLIENT, RPL_LUSEROP, RPL_USERUNKNOWN, RPL_LUSERCHANNELS 및 RPL_LUSERME로부터의 일련의 응답을 보냅니다. 응답할 때 서버는 반드시 RPL_LUSERCLIENT와 RPL_LUSERME를 다시 보내야 합니다. 다른 응답은 해당 응답에 대한 non-zero count가 발견된 경우에만 보내집니다.

<br>

## Example
```
"375 :- Server Message of the Day - "
"372 :- Welcome to the server! Enjoy your stay."
"376 :End of /MOTD command."
``` 
<br>

## TODO
- [x] PASS, NICK, USER 모두 통과 했는지 확인한다.
- [x] nickname, realname, username 이 제대로 들어 있는지 확인한다.
- [x] 숫자 응답을 보낸다.
   - [x] 375
   - [x] 372
   - [x] 376
   - [ ] 251
   - [ ] 253
   - [ ] 254
   - [ ] 255
- [x] NICK 또는 USER 명령어가 실행된 뒤에 구현한 내용을 실행시켜야 한다.
