### ISSUE TITLE
[feat] Channel operations - TOPIC

### ISSUE THREAD

**Issue by LWJ0513** [42Seoul-ft-irc/ft_irc#20]
![포챠코](https://github.com/42Seoul-ft-irc/ft_irc/assets/90092181/dba498de-11e8-4616-b1ac-347b1ac77627)

## Description

```
      Command: TOPIC
   Parameters: <channel> [<topic>]
``` 
채널의 주제를 **변경**하거나 **확인**한다.

- <topic>이 주어지지 않으면 <channel> 채널의 주제가 반환된다.
- <topic> 매개변수가 있으면 해당 채널의 주제가 변경되며, 채널 모드가 이 작업을 허용하는 경우에만 변경된다.
- 채널 오퍼레이터는 주제를 변경할 수 있다.
- 일반 사용자는 채널 모드가 -t 일 때만 수정할 수 있다.
<br>

## Numeric Replies
           ERR_NEEDMOREPARAMS              ERR_NOTONCHANNEL
           RPL_NOTOPIC                     RPL_TOPIC
           ERR_CHANOPRIVSNEEDED

### 461     ERR_NEEDMOREPARAMS
                        "<command> :Not enough parameters"
서버에서 여러 명령에 대한 응답으로 클라이언트에게 전달되며, 충분한 매개변수를 제공하지 않았음을 나타냅니다.

### 442     ERR_NOTONCHANNEL
                        "<channel> :You're not on that channel"

클라이언트가 해당 채널의 멤버가 아닌데도 채널에 영향을 미치는 명령을 수행하려고 시도할 때 서버에서 반환됩니다.

### 331     RPL_NOTOPIC
                        "<channel> :No topic is set"

### 332     RPL_TOPIC
                        "<channel> :<topic>"

채널 주제를 확인하기 위해 TOPIC 메시지를 전송할 때 두 가지 응답 중 하나가 전송됩니다.
주제가 설정된 경우 RPL_TOPIC이 반환되고, 그렇지 않으면 RPL_NOTOPIC이 반환됩니다.

### 482     ERR_CHANOPRIVSNEEDED
                        "<channel> :You're not channel operator"

chanop' 권한이 필요한 명령(예: MODE 메시지)을 시도하는 클라이언트가 지정된 채널에서 chanop이 아닌 경우, 이 오류를 반환합니다.
<br>

## Example
```
:Wiz TOPIC #test :New topic     ;User Wiz setting the topic.

TOPIC #test :another topic      ;set the topic on #test to "another topic".

TOPIC #test                     ; check the topic for #test.
``` 
<br>

##  🤔❓
- `:Wiz TOPIC #test :New topic` 와 같이 닉네임이 앞에 붙어 들어올 경우,.. 가 없는데 꼭 해야할까?

<br>

## TODO
- [x] active 검사
- [x] 메세지 파싱
   - [x] 파라미터가 없을 경우 461 ERR_NEEDMOREPARAMS 발생
   - [x] 없는 채널일 때 403 발생
         -  파라미터로 한 개만 들어오게 irssi 에서 처리 됨. 나머지는 trailing으로 추가됨
- [x] 토픽 조회 `/topic #있는방이름` 
   - [x] 토픽이 없으면 331
   - [x] 토픽이 있으면 332
- [x] 토픽 수정
   - [x] join한 채널인지 검사
      - [x] join 안 했으면 442
      - [x] join 하고 일반 사용자면
         - [x] mode +t 면 수정 불가능 482
         - [x] mode -면 수정 가능 `:sooyang!root@127.0.0.1 TOPIC #hi :b`
      - [x] join 하고 운영자면 토픽 수정
 - [x] 토픽 변경시 해당 채널에 있는 모두에게 응답 전송
    `:wonlim!root@127.0.0.1 TOPIC #hi2 :a`
 - [x] 만약 토픽을 똑같은 내용으로 변경 요청이 들어오면 무시
