### ISSUE TITLE
[feat] Channel operations - MODE

### ISSUE THREAD

**Issue by LWJ0513** [42Seoul-ft-irc/ft_irc#22]
## Description

```
    Command: MODE
 Parameters: <channel> {[+|-]|o|p|s|i|t|n|b|v} [<limit>] [<user>] [<ban mask>]
``` 
사용자 이름과 채널의 모드를 변경

### Channel modes
```
   Parameters: <channel> {[+|-]|o|p|s|i|t|n|b|v} [<limit>] [<user>]
               [<ban mask>]
``` 

- [ ]  i : 초대만 가능한 채널 설정/삭제
- [ ]  t : 채널 운영자의 TOPIC 커맨드 제한 설정/삭제
- [ ]  k : 채널 비번 설정/삭제
- [ ]  o : 채널 관리자 권한 받기/주기
- [ ]  l: 채널 이용 가능 사용자 수 Set/remove

- 채널 운영자가 `자신의' 채널의 특성을 변경할 수 있도록 제공됩니다.
- 또한 채널 운영자를 생성할 수 있도록 서버가 채널 모드를 변경할 수 있어야 합니다. ???
- ‘o’는 세 번까지만 가능하다

		o - 채널 운영자 권한 부여/해제;
		i - 초대 전용 채널 플래그;
		t - 주제 설정 가능한 채널 운영자 전용 플래그;
		l - 채널의 사용자 인원 수 제한 설정;
		k - 채널 키(암호) 설정.

## Example
```
MODE #Finnish +im               ; Makes #Finnish channel moderated and
                                'invite-only'.

MODE #Finnish +o Kilroy         ; Gives 'chanop' privileges to Kilroy on 
																channel #Finnish.

MODE #42 +k oulu                ; Set the channel key to "oulu".

MODE #eu-opers +l 10            ; Set the limit for the number of users
                                on channel to 10.
``` 

## TODO
- [ ]
